### ISSUE TITLE
MongoDB - TypeError: Cannot read property 'collection' of undefined

### ISSUE THREAD

**Issue by manuel-di-iorio** [biggora/caminte#78]
What is this error about ?

	App\caminte\lib\adapters\mongodb.js:122
		if(this.client.collection) {
					  ^

	TypeError: Cannot read property 'collection' of undefined
		at MongoDB.collection (App\caminte\lib\adapters\mongodb.js:122:19)
		at App\caminte\lib\adapters\mongodb.js:111:22
		at Array.forEach (native)
		at null._onTimeout (App\caminte\lib\adapters\mongodb.js:103:39)
		at Timer.listOnTimeout (timers.js:92:15)

---

Into my MongoDB, I have the collection: "users".

The server code:

	var caminte = require('caminte'),
		Schema = caminte.Schema,
		config = {
			driver     : "mongodb",
			host       : "host",
			port       : "port",
			username   : "username",
			password   : "password",
			database   : "db",
			pool       : true
		};

	var schema = new Schema(config.driver, config);

	//define the models
	var User = schema.define('user', {
		email:				{type: schema.String, unique: true},
		password:			schema.String,
		joinedAt:     		{type: schema.Date, default: Date.now}
	});
	
	User.validatesPresenceOf('email');
	User.validatesLengthOf('password', {min: 7});
	User.validatesUniquenessOf('email');

    var Address = schema.define('addresse', {
		name:	{type: String, index: true},
	});

---

**Update:**

The problem is related to: `email: {type: schema.String, unique: true},`, particularly to `unique: true`. When removing the _unique_ type, the error will not be thrown. Why?

**Update 2:**

Also, the same problem appears when adding _index: true_ to `name: {type: String, index: true}` (in the Address model)

**Comment by samirbr** [comment]
The issue is cause because mongodb adapter [define](https://github.com/biggora/caminte/blob/master/lib/adapters/mongodb.js#L97) method is called before the actual connection to the database is completed consequently this.client is undefined. A greater [timeout](https://github.com/biggora/caminte/blob/master/lib/adapters/mongodb.js#L102) can make it pass without throwing the error, but its not a good approach.

**Comment by webmaven** [comment]
So, can this issue be closed?

**Comment by manuel-di-iorio** [comment]
@webmaven, @samirbr said to increase the timeout inside the define method. 
Is the commit with the fix pushed? Also, is there a way to not use a timeout and instead a more reliable connection event?

**Comment by samirbr** [comment]
I made a PR #120 to fix the issue.

**Comment by webmaven** [comment]
PR #120 has been merged, can this issue be closed?

**Comment by mikenicholls88** [comment]
Hi thanks, we are still seeing these errors. Has the fix been merged to the current version. We have updated our package.json to use the latest caminte but didnt seem to fix. Thanks Mike

**Comment by Nihilivin** [comment]
I tested a little something:
```javascript
MongoDB.prototype.define = function (descr) {
    if (!descr.settings)
        descr.settings = {};
    var self = this;
    this._models[descr.model.modelName] = descr;
    this.connection().then(function() {
        Object.keys(descr.properties).forEach(function (k) {
	    if (typeof descr.properties[k].index !== 'undefined' || typeof\
 descr.properties[k].unique !== 'undefined') {
                var fields = {}, params = {};
                fields[k] = 1;
                params['name'] = '_' + k + '_';
                if (typeof descr.properties[k].unique !== 'undefined') {
                    params['unique'] = true;
                }
                self.collection(descr.model.modelName).ensureIndex(fields,\
 params);
            }
        });
    }).catch(e => console.error);
};
```

Simply adding the `catch` on the `connection` Promise solves this issue for me.
